environment:
  nodejs_version: "12"

install:
  - ps: Install-Product node 12
  - npm install -g npm
  - npm --version
  - node --version
  - cd gui
  - npm ci --no-optional

# This is the "test phase", tweak it as you see fit
test_script:
  - npm run lint
  - npm run build
  - npm test

# Stops feature branches from triggering two builds (One for branch and one for PR)
skip_branch_with_pr: true

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

# We build in the test stage, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
build: false
