[package]
name = "talpid-openvpn-plugin"
version = "2019.9.0"
authors = [
    "Mullvad VPN <admin@mullvad.net>",
    "Andrej Mihajlov <and@mullvad.net>",
    "Emīls Piņķis <emils@mullvad.net>",
    "Erik Larkö <erik@mullvad.net>",
    "Janito Vaqueiro Ferreira Filho <janito@mullvad.net>",
    "Linus Färnstrand <linus@mullvad.net>",
]
description = "OpenVPN shared library plugin for relaying OpenVPN events to talpid_core"
license = "GPL-3.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
err-derive = "0.1.5"
log = "0.4"
env_logger = "0.6"
jsonrpc-client-core = { git = "https://github.com/mullvad/jsonrpc-client-rs", rev = "68aac55b" }
jsonrpc-client-ipc = { git = "https://github.com/mullvad/jsonrpc-client-rs", rev = "68aac55b" }
tokio-reactor = "0.1"
tokio = "0.1"
futures = "0.1"

openvpn-plugin = { git = "https://github.com/mullvad/openvpn-plugin-rs", branch = "auth-failed-event", features = ["serde", "log"] }
talpid-ipc = { path = "../talpid-ipc" }
talpid-types = { path = "../talpid-types" }


[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"

[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Amagicom AB"
LegalCopyright = "(c) 2018 Amagicom AB"
InternalName = "talpid-openvpn-plugin"
OriginalFilename = "talpid_openvpn_plugin.dll"
